// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AnalyzeAudio(arg1:string):Promise<types.AudioFingerprint>;

export function AppVersion():Promise<string>;

export function BrainCancel(arg1:string):Promise<void>;

export function BrainRun(arg1:types.BrainRequest):Promise<types.BrainResult>;

export function BrainStatus(arg1:string):Promise<types.BrainStatus>;

export function BrainTest(arg1:string,arg2:types.LocalOpts):Promise<types.BrainResult>;

export function ClaudeCLIInstalled():Promise<boolean>;

export function ConnectClaudeAccount():Promise<string>;

export function ConnectCodexAccount():Promise<string>;

export function CopyText(arg1:string):Promise<void>;

export function CreateProject(arg1:string):Promise<types.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function EmitAbout():Promise<void>;

export function EmitBrainRefresh():Promise<void>;

export function EmitHelp():Promise<void>;

export function FileAsDataURL(arg1:string):Promise<string>;

export function GetPlatform():Promise<string>;

export function IngestMedia(arg1:string,arg2:string):Promise<types.MediaIngestResult>;

export function ListProjects():Promise<Array<types.ProjectMeta>>;

export function LocalModels(arg1:string):Promise<types.LocalModelsResult>;

export function MenuConnectClaude():Promise<void>;

export function MenuConnectCodex():Promise<void>;

export function MenuRefreshBrain():Promise<void>;

export function MenuTestClaude():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<types.Project>;

export function PickAudio():Promise<Array<string>>;

export function PickMedia():Promise<Array<string>>;

export function RevealProject(arg1:string):Promise<void>;

export function SaveProject(arg1:types.Project):Promise<void>;

export function StillsDiscover():Promise<Array<types.CircledTake>>;

export function StillsExtract(arg1:string,arg2:string,arg3:any,arg4:any):Promise<Array<string>>;

export function TestClaudeBrain():Promise<types.BrainResult>;
