// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeAudio(arg1) {
  return window['go']['main']['App']['AnalyzeAudio'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BrainCancel(arg1) {
  return window['go']['main']['App']['BrainCancel'](arg1);
}

export function BrainRun(arg1) {
  return window['go']['main']['App']['BrainRun'](arg1);
}

export function BrainStatus(arg1) {
  return window['go']['main']['App']['BrainStatus'](arg1);
}

export function BrainTest(arg1, arg2) {
  return window['go']['main']['App']['BrainTest'](arg1, arg2);
}

export function ClaudeCLIInstalled() {
  return window['go']['main']['App']['ClaudeCLIInstalled']();
}

export function ConnectClaudeAccount() {
  return window['go']['main']['App']['ConnectClaudeAccount']();
}

export function ConnectCodexAccount() {
  return window['go']['main']['App']['ConnectCodexAccount']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function EmitAbout() {
  return window['go']['main']['App']['EmitAbout']();
}

export function EmitBrainRefresh() {
  return window['go']['main']['App']['EmitBrainRefresh']();
}

export function EmitHelp() {
  return window['go']['main']['App']['EmitHelp']();
}

export function FileAsDataURL(arg1) {
  return window['go']['main']['App']['FileAsDataURL'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function IngestMedia(arg1, arg2) {
  return window['go']['main']['App']['IngestMedia'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LocalModels(arg1) {
  return window['go']['main']['App']['LocalModels'](arg1);
}

export function MenuConnectClaude() {
  return window['go']['main']['App']['MenuConnectClaude']();
}

export function MenuConnectCodex() {
  return window['go']['main']['App']['MenuConnectCodex']();
}

export function MenuRefreshBrain() {
  return window['go']['main']['App']['MenuRefreshBrain']();
}

export function MenuTestClaude() {
  return window['go']['main']['App']['MenuTestClaude']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PickAudio() {
  return window['go']['main']['App']['PickAudio']();
}

export function PickMedia() {
  return window['go']['main']['App']['PickMedia']();
}

export function RevealProject(arg1) {
  return window['go']['main']['App']['RevealProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function StillsDiscover() {
  return window['go']['main']['App']['StillsDiscover']();
}

export function StillsExtract(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StillsExtract'](arg1, arg2, arg3, arg4);
}

export function TestClaudeBrain() {
  return window['go']['main']['App']['TestClaudeBrain']();
}
