// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {audit} from '../models';

export function CheckForUpdates():Promise<update.CheckResult>;

export function GetInstallStatus():Promise<Record<string, any>>;

export function GetPaths():Promise<Record<string, string>>;

export function InstallClaude():Promise<Record<string, any>>;

export function LaunchApp():Promise<void>;

export function LaunchClaudeLogin():Promise<string>;

export function LogPath():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenLogFolder():Promise<void>;

export function OpenProjectsFolder():Promise<void>;

export function PickInstallFolder(arg1:string):Promise<string>;

export function RunAudit():Promise<audit.Report>;

export function StartInstall(arg1:string,arg2:boolean,arg3:boolean):Promise<Record<string, any>>;

export function Uninstall():Promise<Record<string, any>>;
