// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetInstallStatus() {
  return window['go']['main']['App']['GetInstallStatus']();
}

export function GetPaths() {
  return window['go']['main']['App']['GetPaths']();
}

export function InstallClaude() {
  return window['go']['main']['App']['InstallClaude']();
}

export function LaunchApp() {
  return window['go']['main']['App']['LaunchApp']();
}

export function LaunchClaudeLogin() {
  return window['go']['main']['App']['LaunchClaudeLogin']();
}

export function LogPath() {
  return window['go']['main']['App']['LogPath']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function OpenProjectsFolder() {
  return window['go']['main']['App']['OpenProjectsFolder']();
}

export function PickInstallFolder(arg1) {
  return window['go']['main']['App']['PickInstallFolder'](arg1);
}

export function RunAudit() {
  return window['go']['main']['App']['RunAudit']();
}

export function StartInstall(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartInstall'](arg1, arg2, arg3);
}

export function Uninstall() {
  return window['go']['main']['App']['Uninstall']();
}
